### ISSUE TITLE
Why there is sometimes appearing error on tau[0] == tau[1]

### ISSUE THREAD

**Issue by hsiehjackson** [HIIT/Ledapy#1]
![image](https://user-images.githubusercontent.com/37269846/48356641-a7a59480-e6d1-11e8-872e-c6f9f3d41274.png)

I want to ask when I set optimization = 2, why there will be sometimes appearing errors about tau value.
Thank you!

**Comment by MarcoFiletti** [comment]
Interesting, it would be nice if you could send me some sample data which raises this issue. tau1 and tau2 should always be different, but in this case they end up being set at the same value by the optimiser. I can also see that there is a bug in the output (the error message is not formatter properly).

**Comment by hsiehjackson** [comment]
Thanks for your help and reply! Following is a sample data which the EDA signal measurement is us. When I use matlab to run the optimization, there would be no error messages. 
https://goo.gl/7oEejN

**Comment by MarcoFiletti** [comment]
Hi, I didn't manage to reproduce the issue; this is what I did

checked python version:
`python --version`  (or `python3 --version`)
should be 3 and above, mine is `Python 3.7.0`

cloned repository as ledapy
`git clone https://github.com/HIIT/Ledapy ledapy`

copied your sample in ledapy as `test.csv`

then in python
```
import ledapy
import numpy
import scipy.io as sio
import matplotlib.pyplot as plt
from numpy import array as npa
filename = 'ledapy/test.csv'
sampling_rate = 100  # note: what is the sampling rate?
csv_data = numpy.genfromtxt(filename, delimiter=',')
phasicdata = ledapy.runner.getResult(csv_data, 'phasicdata', sampling_rate, downsample=4, optimisation=2)
plt.plot(phasicdata)
plt.show()
```

I get a result that seems correct

**Comment by hsiehjackson** [comment]
The sampling_rate is 128
and I set the downsample = 8 
Sorry I forget to give you the information

**Comment by MarcoFiletti** [comment]
Ok I see, it may take me a long time to debug this issue, also considering that I don't have a Matlab license right now to compare results with Ledalab.

A temporary solution could be to use a downsample value of 2, which works in this case. The downsample value can be adjusted depending on the size of the input (the data segment of the sample data is already quite short, so it doesn't need much downsampling).

**Comment by kauttoj** [comment]
Hi. Thanks for the port, much appreciated! 

I also have problems with Tau1 == Tau2. I have a GSR signal with duration 117sec with sampling rate 125Hz. For this signal I tested deconvolution with varying sampling rates and optimization iteration counts, here is the result:

```
Sampling rate 5Hz and optimizations 1: Success
Sampling rate 5Hz and optimizations 2: Success
Sampling rate 5Hz and optimizations 3: Success
Sampling rate 5Hz and optimizations 4: Success
Sampling rate 8Hz and optimizations 1: Success
Sampling rate 8Hz and optimizations 2: FAILED! (tau1 == tau2 == 1.000000)
Sampling rate 8Hz and optimizations 3: FAILED! (tau1 == tau2 == 1.000000)
Sampling rate 8Hz and optimizations 4: FAILED! (tau1 == tau2 == 1.000000)
Sampling rate 12Hz and optimizations 1: Success
Sampling rate 12Hz and optimizations 2: FAILED! (tau1 == tau2 == 1.000000)
Sampling rate 12Hz and optimizations 3: FAILED! (tau1 == tau2 == 1.000000)
Sampling rate 12Hz and optimizations 4: FAILED! (tau1 == tau2 == 1.000000)
Sampling rate 17Hz and optimizations 1: Success
Sampling rate 17Hz and optimizations 2: FAILED! (tau1 == tau2 == 1.000000)
Sampling rate 17Hz and optimizations 3: FAILED! (tau1 == tau2 == 1.000000)
Sampling rate 17Hz and optimizations 4: FAILED! (tau1 == tau2 == 1.000000)
Sampling rate 21Hz and optimizations 1: Success
Sampling rate 21Hz and optimizations 2: Success
Sampling rate 21Hz and optimizations 3: Success
Sampling rate 21Hz and optimizations 4: Success
Sampling rate 24Hz and optimizations 1: Success
Sampling rate 24Hz and optimizations 2: FAILED! (tau1 == tau2 == 1.000000)
Sampling rate 24Hz and optimizations 3: FAILED! (tau1 == tau2 == 1.000000)
Sampling rate 24Hz and optimizations 4: FAILED! (tau1 == tau2 == 1.000000)
```

I simply interpolated my original signal for different rates and then ran command:

`phasic = ledapy.runner.getResult(yy,'phasicdata',rate,downsample=1,optimisation=N_opt)`

where N_opt was 1-4. 

So there is something weird going on with the algorithm. There should be no reason why it works with rate 21Hz but fails with 24Hz. I'm running Python 3.7.3.

In case you/someone wants to try, here are data for one good and one bad case:
[Sampling rate 21Hz and optimizations 3: Success](https://drive.google.com/open?id=18SQmjUokPcLFeRHna_hawkEypvWoGOj5)
[Sampling rate 24Hz and optimizations 3: FAILED!](https://drive.google.com/open?id=1miaOM0VwC72wmFRJh3K95yutAeyWBQh5)

**Comment by MarcoFiletti** [comment]
Hello, I think I found the issue, the latest version (1.1) should now work, at least with the files you provided. You could run your full test suite to make sure the results are now as expected.

**Comment by kauttoj** [comment]
All my tests for this data passed using version 1.1. However, I still get warning 

`analyse.py:42: RankWarning: Polyfit may be poorly conditioned  [x, newerror, step] = cgd_linesearch(x, olderror, direction, error_fcn, h)`

for some sampling rates, which indicates some numerical stability/convergence issues. Sampling rate still have some unexpected effects on computations. 
But there are no errors and results seem ok, so this issue appears fixed for now. Thank you!

**Comment by MarcoFiletti** [comment]
Alright, I'll have a look. Does the final output (returned by getResult) look particularly different when you get that warning?

**Comment by kauttoj** [comment]
The results seems similar so it's not bad despite getting the warning.
Here are couple of plots for the "FAILED" data above. I ran phasic computing using different sampling rates (identical input data) with optimization steps set at 3 and no downsampling:
![test_corrmat](https://user-images.githubusercontent.com/17804946/62470844-fdf8bd00-b7a3-11e9-90d8-409becf7b32e.png)
![test_signals](https://user-images.githubusercontent.com/17804946/62470846-fdf8bd00-b7a3-11e9-8e17-55df092d1a5d.png)
First shows the Pearson correlations and the second estimated signals with all "bad rank" result highlighted [I also shifted signal by stepping 0.015 in y-dir for easier visualization].

**Comment by MarcoFiletti** [comment]
Very nice, thanks! I'll have a look to see how Ledalab deals with that fitting. In the meantime I can close this issue

**Comment by MarcoFiletti** [comment]
Hello, I did investigate, actually I found a slight issue in that function when comparing with Matlab. I updated the package to version 1.2. Not sure if it will fix the warning, but at least now that function behaves the same as in Matlab

**Comment by kauttoj** [comment]
I think you fixed it, no more warnings and the results seem more consistent (higher cross-correlations). Here are the same plots with the latest version:
![test_corrmat](https://user-images.githubusercontent.com/17804946/62518700-c9801200-b832-11e9-95f0-3f33340221f2.png)
![test_signals](https://user-images.githubusercontent.com/17804946/62518702-ca18a880-b832-11e9-86b6-642beb74b437.png)

**Comment by MarcoFiletti** [comment]
Alright, thank you for running the tests!
